dist: trusty
sudo: required

addons:
  sonarqube:
    token:
      secure: "OQaO+ZjILkgXMOVeAwTLngevPPn2jlipNtXs8Q5ODIwGGGlHHXkIQX5xlbL6LjiKLWorsiffGpEuL+5rlwdWhPcYw7xCku1gb6RBdw/yu/17zpBJE9ZjaU1xglYtdSmqjNQxR4E79X3TYIjO3BpjEmP8Pq0dXEjsYFaZuVPvDebOQf1DPs155H58HQGF+29+5/l81ylrQ24fTZbGBOIZtSKVpyor77Wk9bpP9x1hPq5yRjAZK8MAXXypiCSS3Iekxn0ymZHh+fm/CVTINRn0bIPaF/I/vu4ScJSzp91hpjOPRBUu/OODf8ttdBfhoykFX1ijUWuXVu2naeo4+jdYMaNL5npDkJ5EuxkHo/ainZJbVdH9i08aB0yFNPWG1z+Ic8ovDfgMvmPfCtPcsy+WENNVmlrfgMQwwzZ9oWqSsGba2cm3Jez1xwNHVzfTR4ne78iDg60s9H4tWxBhoEM9b0HNf/A/Y8HDEKHxvmnG+lzWQAF1o+bdIZvtr8Vxb/waH+k4N24cXYNPtlMHOBwpvTIwrpf8USrzmYpoKLdBUpQLulW9VabpPaNSgyvIrjlnXmTsIQ8poYHH/ICHZStRZHQO6ujKCjZfGtqR+3VLkl2pkbtQ+1U41uoeoYqUy1XwYzDfTWylvK8sQHv45tm4fxjbJLgLtjHEqqm4sstmQTs="
    github_token:
      secure: "hfDyW7WSK/FX4f8IqypWSCpbXblq6urFoQw28rGW1BQlIghAPFeQ8PeIl7j3X468j/yFO+ZwvIhCkhlJ6+NfZaI0w6yHQs15x18+xWjf2GCpRif0mlQaSP5NnpPrUep7Ld01E2by/1ZWMKiau3odMmDmUNc3f1CJl8w1qV/PSTJ6oSpaFU/G/VnBLC+IujKXqA8c5W070gECZfdpg5Q+zNbsJ0OqbpZLzD8accfS7lXjGitiBMHNvb2vjJl76k14kKZoC5EJxVT3EvqoO8MQngvfaqQwbIq9d0cNphusZuoXKy7cTUpmF+ZtdqVt0uxkNL75cU717I9O95cvuFRg10/emy/HMxJA5tk10nUNeXWfqgimKe4/34VANTb3+Vb/xG/n53JB8/SMivxhGG5lJ1MGQ2v5umM23V2fupauRCf0mRDvqsKua9NZTyUL3WIUpkGa8wrXHEb7dNNmdty+g8TNcG0ojoOeL/IyTWrvVa0YPmwdmnpAYJ6tSAlhOu7ai4KdNvO+NXFOEebaV7YxMoyzvVB73Xi9jyeu4bLumwxZMZOpH6rppJzS7wZt/S+SvKgY07bekbIXuPY6/zvVFDNShqo4I8eIjuBB+aQRXdKlTroaklWU+TdZ7OZQ5tC8yYaN5QyWs/16xrwtVOCKKIeK4a2ibOeDLs6idNTARt4="


language: node_js
node_js:
  - "6"
before_script:
  - npm install -g gulp
script: gulp test

jdk:
  - oraclejdk8

script:
  - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'
