language: node_js
node_js:
- '6'
dist: trusty
sudo: required
addons:
  sonarqube:

before_script:
- npm install -g gulp
script:
- gulp test
after_success:
- gulp cover-coveralls
- sonar-scanner
   