dist: trusty
sudo: required

addons:
  sonarqube:
    token:
      secure: SONAR_TOKEN

language: node_js
node_js:
  - "6"
before_script:
  - npm install -g gulp
script: gulp test

jdk:
  - oraclejdk8

script:
  - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'
